apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
  type: LoadBalancer
  selector:
    app: payment