apiVersion: v1
kind: Service
metadata:
  name: rental
  labels:
    app: rental
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8083
  type: LoadBalancer
  selector:
    app: rental